# Generated by Django 6.0.1 on 2026-01-18 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rath_api', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='rath_api.driverprofile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='rath_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('CUSTOMER', 'Customer'), ('AGENT', 'Agent')], default='CUSTOMER', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='rath_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
