# Generated by Django 6.0.1 on 2026-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rath_api', '0002_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Driver'), ('AGENT', 'Agent')], default='CUSTOMER', max_length=10),
        ),
    ]
